# Matrices

In [1]:
import numpy as np

1. Soient les matrices $A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$ et $B = \begin{pmatrix} -1 & 0 \\ 0 & 1 \end{pmatrix}$. Calculer $A + B$ et $A - B$.


In [2]:
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[-1, 0],
              [0, 1]])

print(A + B)
print(A - B)

[[0 2]
 [3 5]]
[[2 2]
 [3 3]]


2. Calculer le produit des matrices $A = \begin{pmatrix} 2 & -1 \\ 0 & 3 \end{pmatrix}$ et $B = \begin{pmatrix} 1 & 4 \\ -2 & 5 \end{pmatrix}$.


In [17]:
A = np.array([[2, -1],
              [0, 3]])
B = np.array([[1, 4],
              [-2, 5]])

print(A @ B)

[[ 4  3]
 [-6 15]]


3. Soit la matrice $C = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix}$. Calculer la transposée de $C$, notée $C^T$.


In [7]:
C = np.array([[1, 2, 3],
              [4, 5, 6]])
D = C.T

print(D)

[[1 4]
 [2 5]
 [3 6]]


4. Trouver la trace de la matrice $D = \begin{pmatrix} 2 & 0 & -1 \\ 4 & 3 & 5 \\ 0 & 1 & -2 \end{pmatrix}$.


In [9]:
D = np.array([[2, 0, -1],
              [4, 3, 5],
              [0, 1, -2]])

trace_D = np.trace(D)
print(trace_D)


3


5. Soit la matrice $E = \begin{pmatrix} 1 & 2 \\ 2 & 4 \end{pmatrix}$. Déterminer le rang de $E$.


In [10]:
E = np.array([[1, 2],
              [2, 4]])

rank_E = np.linalg.matrix_rank(E)
print(rank_E)

1


6. Vérifier si la multiplication des matrices 
$A = \begin{pmatrix} 1 & 0 & -2 \\ 3 & 5 & 1 \end{pmatrix}$
et
$B = \begin{pmatrix} 2 & 3 \\ -1 & 4 \\ 0 & 5 \end{pmatrix}$
est possible. Si oui, calculer le produit A x B




In [11]:
A = np.array([[1, 0, -2],
            [3, 5, 1]])
B = np.array([[2, 3],
              [-1, 4],
              [0, 5]])

C = A @ B
print(C)

[[ 2 -7]
 [ 1 34]]


7. Soit la matrice $F = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$. Calculer $F^T \times F$.


In [14]:
F = np.array([[1, 2],
              [3, 4]])

F_T = F.T

print(F_T @ F)

[[10 14]
 [14 20]]


8. Déterminer si la matrice 
$G = \begin{pmatrix} 2 & -1 & 0 \\ -1 & 2 & -1 \\ 0 & -1 & 2 \end{pmatrix}$ 
est symétrique.

In [ ]:
G = np.array([[2, -1, 0],
                [-1, 2, -1],
                [0, -1, 2]])

is_symmetric = np.array_equal(G, G.T)
print(is_symmetric)


True


9. Soit la matrice $H = \begin{pmatrix} 1 & 2 & 3 \\ 0 & 0 & 0 \\ 4 & 5 & 6 \end{pmatrix}$. Déterminer le rang de $H$.

In [ ]:
H = np.array([[1, 2, 3],
              [0, 0, 0],
              [4, 5, 6]])


rank_H = np.linalg.matrix_rank(H)
print(rank_H)

2
