# Vecteurs



1. Soient les vecteurs $\vec{u} =
\begin{pmatrix}
2 \\
-1 \\
3
\end{pmatrix}$
et $\vec{v} =
\begin{pmatrix}
-1 \\
4 \\
0
\end{pmatrix}$.
Calculer $\vec{u} + \vec{v}$ et $\vec{u} - \vec{v}$.


In [1]:
import numpy as np
u = np.array([2, -1, 3])
v = np.array([-1, 4, 0])
j = u + v
y = u - v
print(y)
print(j)

[ 3 -5  3]
[1 3 3]


2. Calculer le produit scalaire des vecteurs :
   $$
   \vec{a} =
   \begin{pmatrix}
   1 \\
   2 \\
   3
   \end{pmatrix},
   \quad
   \vec{b} =
   \begin{pmatrix}
   4 \\
   -5 \\
   6
   \end{pmatrix}
   $$
   En déduire l’angle $\theta$ entre $\vec{a}$ et $\vec{b}$ en utilisant la formule :
   $$
   \vec{a} \cdot \vec{b} = \|\vec{a}\| \|\vec{b}\| \cos\theta
   $$


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, -5, 6])
c = np.dot(a, b)
print(c)

12


3. Soient $\vec{a} = \begin{pmatrix} 3 \\ 0 \\ -2 \end{pmatrix}$ et  $\vec{b} = \begin{pmatrix} -1 \\ 5 \\ 4 \end{pmatrix}$ Calculer $2\vec{a} - 3\vec{b}$



In [3]:
a = np.array([3, 0, -2])
b = np.array([-1, 5, 4])
c = 2*a - 3*b
print(c)

[  9 -15 -16]


4. Déterminer si les vecteurs $\vec{u}=\begin{pmatrix} 1\\2\\3\end{pmatrix}$ 
et $\vec{v}=\begin{pmatrix} 2\\4\\6 \end{pmatrix}$ sont colinéaires?

Oui ils sont colinéaires parce que 2 $\vec{u}$ = $\vec{v}$