# Vecteurs



In [12]:
import numpy as np

1. Soient les vecteurs $\vec{u} =
\begin{pmatrix}
2 \\
-1 \\
3
\end{pmatrix}$
et $\vec{v} =
\begin{pmatrix}
-1 \\
4 \\
0
\end{pmatrix}$.
Calculer $\vec{u} + \vec{v}$ et $\vec{u} - \vec{v}$.


In [13]:
u = np.array([2, -1, 3])
v = np.array([-1, 4, 0])
j = u + v
y = u - v
print(y)
print(j)

[ 3 -5  3]
[1 3 3]


2. Calculer le produit scalaire des vecteurs $\vec{a} = \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}$ et $\vec{b} = \begin{pmatrix} 4 \\ -5 \\ 6 \end{pmatrix}$. En déduire l’angle $\theta$ entre $\vec{a}$ et $\vec{b}$ en utilisant la formule $\vec{a} \cdot \vec{b} = \|\vec{a}\| \|\vec{b}\| \cos\theta$.



In [18]:
a = np.array([1, 2, 3])
b = np.array([4, -5, 6])

dot_product = np.dot(a, b)

norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)

cos_theta = dot_product / (norm_a * norm_b)
theta_rad = np.arccos(cos_theta)
theta_deg = np.degrees(theta_rad)
print(theta_deg)

68.56244696639715


3. Soient $\vec{a} = \begin{pmatrix} 3 \\ 0 \\ -2 \end{pmatrix}$ et  $\vec{b} = \begin{pmatrix} -1 \\ 5 \\ 4 \end{pmatrix}$ Calculer $2\vec{a} - 3\vec{b}$



In [15]:
a = np.array([3, 0, -2])
b = np.array([-1, 5, 4])
c = 2*a - 3*b
print(c)

[  9 -15 -16]


4. Déterminer si les vecteurs $\vec{u}=\begin{pmatrix} 1\\2\\3\end{pmatrix}$ 
et $\vec{v}=\begin{pmatrix} 2\\4\\6 \end{pmatrix}$ sont colinéaires?

Oui ils sont colinéaires parce que 2 $\vec{u}$ = $\vec{v}$

5. Soient les vecteurs $\vec{u} = \begin{pmatrix} 2 \\ -1 \end{pmatrix}$ et $\vec{v} = \begin{pmatrix} -3 \\ 5 \end{pmatrix}$. Calculer le produit scalaire $\vec{u} \cdot \vec{v}$ ainsi que les normes $\|\vec{u}\|$ et $\|\vec{v}\|$.



In [16]:
u = np.array([2, -1])
v = np.array([-3, 5])

c = u.dot(v)
print(c)
u_norm = np.linalg.norm(u)
v_norm = np.linalg.norm(v)

print(u_norm)
print(v_norm)


-11
2.23606797749979
5.830951894845301


6. Soient les vecteurs $\vec{a} = \begin{pmatrix} 1 \\ 0 \\ -1 \end{pmatrix}$ et $\vec{b} = \begin{pmatrix} 0 \\ 1 \\ 1 \end{pmatrix}$. Calculer le produit vectoriel $\vec{a} \times \vec{b}$.



In [17]:
a = np.array([1,0,-1])
b = np.array([0,1,1])

c = np.cross(a, b)
print(c)

[ 1 -1  1]


7. Soient les vecteurs $\vec{u} = \begin{pmatrix} a \\ 2 \\ -1 \end{pmatrix}$ et $\vec{v} = \begin{pmatrix} 1 \\ -1 \\ b \end{pmatrix}$. Déterminer les réels $a$ et $b$ tels que $\vec{u}$ et $\vec{v}$ soient orthogonaux.


Pour que les vecteurs soient orthogonaux, il faut que leur produit scalaire soient nuls. 
Donc a -2 -b = 0. Ce qui veut dire qu'on a une infinité de solutions.  